name: Build and push container

# Use this workflow to:
# - Manually build and push the Dockerfile
# - Automatically build and push on certain changes

# TODO: Automate build and push for cutting a release

# TODO: Decide when/where/how to push major tag

on:
  # Run when manually triggered
  workflow_dispatch:

  # Run when one of these files change
  push:
    paths:
      - Dockerfile
      - entrypoint.sh
      - requirements.txt
      - octodns-requirements.txt
      - .github/workflows/docker.yml

  # Run after version tag is pushed
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      fullref: ${{ steps.getshortref.outputs.fullref }}
      shortref: ${{ steps.getshortref.outputs.shortref }}
      tagbuilt: ${{ steps.buildimage.outputs.tagbuilt }}
      tagpushed: ${{ steps.pullimage.outputs.tagpushed }}

    steps:
      - uses: actions/checkout@v2

      # Get the short reference name
      - name: Get the short reference name
        id: getshortref
        run: |
          _short_ref=
          # If GITHUB_REF is a branch, use the branch name.
          if [[ "${GITHUB_REF}" == "refs/heads/"* ]]; then
            _short_ref=${GITHUB_REF#refs/heads/}
            # If _short_ref is main, use latest instead.
            if [ "${_short_ref}" = "main" ]; then
              _short_ref=latest
            fi
          # If GITHUB_REF looks like a version, use the tag name
          # after the leading v. So vX.Y.Z becomes X.Y.Z
          elif [[ "${GITHUB_REF}" == "refs/tags/v"* ]]; then
            _short_ref=${GITHUB_REF#refs/tags/v}
          # If GITHUB_REF didn't match either of those rules, :scream:
          else
            echo "FAIL: Did not recognize GITHUB_REF '${GITHUB_REF}'."
            exit 1
          fi
          echo "Set fullref to '${_full_ref}'."
          echo "Set shortref to '${_short_ref}'."
          echo "::set-output name=fullref::${GITHUB_REF}"
          echo "::set-output name=shortref::${_short_ref}"

      - name: Build image
        id: buildimage
        run: |
          _short_ref="${{ steps.getshortref.outputs.shortref }}"
          _image_tag="ghcr.io/${IMAGE_NAME}:${_short_ref}"
          if [ -r ./Dockerfile ]; then
            echo "Found ./Dockerfile OK."
          else
            echo "FAIL: ./Dockerfile not readable."
            exit 1
          fi
          if docker build . -q -t "${_image_tag}"; then
            echo "Built '${_image_tag}' OK."
          else
            echo "FAIL: Failed to build '${_image_tag}'."
            exit 1
          fi
          echo "::set-output name=tagbuilt::${_image_tag}"

      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.PAT }}" | \
          docker login ghcr.io \
          -u ${{ github.actor }} --password-stdin

      - name: Push image to ghcr.io
        id: pushimage
        run: |
          _image_tag="${{ steps.buildimage.outputs.tagbuilt }}"
          if docker push -q "${_image_tag}"; then
            echo "Pushed '${_image_tag}' OK."
          else
            echo "FAIL: Failed to push '${_image_tag}'."
            exit 1
          fi
          echo "::set-output name=tagpushed::${_image_tag}"
