name: Run octodns-sync to test config

# Use this workflow to:
# - Manually test octodns config
# - Automatically test octodns config

on:
  # Run when manually triggered
  workflow_dispatch:

  # Run on pull request open, reopen, and synchronize
  pull_request:
     branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Test changes to DNS config
        id: octodns-sync
        uses: solvaholic/octodns-sync@issue40
        with:
          config_path: test-config.yaml
      - name: A piece of duct tape
        id: meta
        run: |
          _plan="$(cat ${GITHUB_WORKSPACE}/octodns-sync.plan)"
          _plan="${_plan//'%'/'%25'}"
          _plan="${_plan//$'\n'/'%0A'}"
          _plan="${_plan//$'\r'/'%0D'}" 
          echo "::set-output name=plan::${_plan}"
          _sha="$(echo "${{ github.event.pull_request.head.sha }}" | cut -c 1-7)"
          echo "::set-output name=sha::${_sha}"
      - name: Find Comment
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Automatically generated by octodns-sync
      - name: Add or update PR comment
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## OctoDNS Plan for `${{ steps.meta.outputs.sha }}`

            ${{ steps.meta.outputs.plan }}

            Automatically generated by octodns-sync
          edit-mode: replace
