# Perform release workflow tasks for this repo.

name: Release

on:
  release:
    types: [published]

# A workflow run is made up of 1+ jobs that can run sequentially or in parallel
# Steps represent a sequence of tasks that will be executed as part of a job

jobs:
  # When a release is published, bump the corresponding short tag.
  # For example, when v2.0.4 is published, update v2 to v2.0.4's SHA.
  # TODO: Only run when tag_name matches /v[0-9]+\.[0-9]+\.[0-9]+/.
  # TODO: Only update when the published release is also the latest.
  bumptag:
    runs-on: ubuntu-latest

    steps:
      - name: Create/update the short tag to match the release tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          _repo: ${{ github.repository }}
          _api: https://api.github.com
          _tag_name: ${{ github.event.release.tag_name }}
          _tag_sha: ${{ github.sha }}
        run: |
          echo _tag_sha: ${_tag_sha}
          # Build the pieces of the curl command to use.
          _a="Authorization: token ${GITHUB_TOKEN}"
          _b="{\"ref\": \"refs/tags/${_tag_name%%.*}\","
            _b+=" \"sha\": \"${_tag_sha}\"}"
          _c="${_api}/repos/${_repo}/git/refs"
          # Create the short tag, if it doesn't exist yet.
          curl -sL -XPOST -H "${_a}" -d "${_b}" "${_c}"
          # Revise curl parts for a different call.
          _b="{\"sha\": \"${_tag_sha}\"}"
          _c="${_api}/repos/${_repo}/git/refs/tags/${_tag_name%%.*}"
          # Update the major version tag, for example "v2".
          curl -sL -XPATCH -H "${_a}" -d "${_b}" "${_c}"
