name: Try this repository as an Action

on:
  # Run when manually triggered
  workflow_dispatch:

jobs:
  tryaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: run-the-action
        uses: solvaholic/scaling-succotash@main
        with:
          config_path: public.yaml
